workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(desarrollo|test|produccion)$/'
    - when: never

stages:
  - build

variables:
  REGISTRY: gcr.hcdn.gob.ar
  BACKEND_IMAGE: gcr.hcdn.gob.ar/hcdn/dgis/departamento-de-ingenier-a-de-red/idr-test/backend
  FRONTEND_IMAGE: gcr.hcdn.gob.ar/hcdn/dgis/departamento-de-ingenier-a-de-red/idr-test/frontend

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/backend" \
        --dockerfile "$CI_PROJECT_DIR/backend/Dockerfile" \
        --destination "$BACKEND_IMAGE:latest" \
        --destination "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA" \
        --skip-tls-verify
  tags:
    - rancher

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/frontend" \
        --dockerfile "$CI_PROJECT_DIR/frontend/Dockerfile" \
        --destination "$FRONTEND_IMAGE:latest" \
        --destination "$FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA" \
        --skip-tls-verify
  tags:
    - rancher